### PR TITLE
Apply patch from 67d68d9 by Salja for druid enrage and make druids in combat

### PR DESCRIPTION
**Pull request by lfxgroove**
I applied Saljas patch and made the druid's enter combat when they use the spell, will exit combat a few seconds afterwards as it usually is. Sorry for the big mess with the commits. This should fix #16

### CODE REVIEW

**Comment by Salja** [comment]
thanks i will check this night this, i think yet you have free time to look of onyxia fly XD =)

**Comment by lfxgroove** [comment]
@Salja yeah i've just started looking at it, trying to think of a fix. How do i reset a instance as gm?

**Comment by Salja** [comment]
@lfxgroove have you skype i must wirte with you ^^

**Comment by lfxgroove** [comment]
@Salja Yeah, sure, add lfxgroovarn, state that it's salja :)

**Pull request closed without merging**
