### PR TITLE
Fix mobs fleeing

### PR DESCRIPTION
**Pull request by lfxgroove**
This slows down the mobs fleeing as seen in #2. Perhaps a config value should added for how quick they should run because i couldn't figure out at what the modifier should be. We could also use the `SetWalk()` instead of how it's done right now, i remember booty bay bucaneers walking away, don't know about the other mobs though.

### CODE REVIEW

**Comment by ghost** [comment]
was this implemented in the testing branch? I've tried both master / testing and it doest seem to work.

**Comment by lfxgroove** [comment]
I thunk i can push it to testing with a few modifications later today

**Comment by lfxgroove** [comment]
@stavaren it's up in testing now, would you mind testing and telling if anything's been overlooked?

**Comment by billy1arm** [comment]
What's the status on this, can we go with it ?

**Comment by lfxgroove** [comment]
This is probably not in a correct state at the moment as if i recall correclty i thought the mobs we going to slow instead of the pace i remember them walking away in. But that may be just me. Also, instead of SetVelocity(0.9f) we should probably use SetWalking() but that was too slow in my opinion as i said. My point is that we probably need to do some more research as in should all fleeing mobs have the same speed and is the assistance movement generator the right place to put that code in?

**Comment by billy1arm** [comment]
This has been added to master

**Pull request closed without merging**
