### PR TITLE
fix building on Mac OS X

### PR DESCRIPTION
**Pull request by Leandros**

### CODE REVIEW

**Comment by lfxgroove** [comment]
Looks good to me, @billy1arm would you like to give an ok on this?

**Comment by Leandros** [comment]
I think there are still some changes missing, which I still only have locally stored. I'll commit them later.

**Comment by billy1arm** [comment]
Thanks for that ;)

**Comment by billy1arm** [comment]
@Leandros - Would you mind preparing this same pull for the Rel19 branch ?

**Pull request merged**
