### PR TITLE
Various fixes.

### PR DESCRIPTION
**Pull request by H0zen**
Fixed build for FreeBSD/CLang (FreeBSD 9.3-RELEASE/amd64).
Fixed minor errors in source code.
Added PIC check in FindPCHSupport.cmake.
Removed ACE from tools building system.

### CODE REVIEW

**Comment by billy1arm** [comment]
@H0zen - I have a couple of concerns regarding this PR.
- ACE IS required for Vmap Assembler and Movement Maps as it uses some of the Types from the ACE library.
- FreeBSD has been building ok for a while, so i'm surprised to see a  'fix' for it. Can you explain what the problem was ?

**Comment by H0zen** [comment]
@billy1arm - Regarding your concerns.
- Vmap Assembler and Movement Maps uses some of the Types from the ACE library indeed, but aren't those types already in the vmap static library?
- FreeBSD 9.3/Clang 3.4.1 complains about UNORDERED_MAP typedef:
  <pre>`src/shared/Database/Database.h:806:17: error: no template named 'unordered_map' in namespace 'std'; did you mean 'std::tr1::unordered_map'?
      typedef UNORDERED_MAP<std::string, int> PreparedStmtRegistry;
              ^~~~~~~~~~~~~
              std::tr1::unordered_map
  src/framework/Utilities/UnorderedMapSet.h:100:25: note: expanded from macro 'UNORDERED_MAP'
  #  define UNORDERED_MAP std::unordered_map
                      ^~~~~
  /usr/include/c++/4.2/tr1/unordered_map:51:11: note: 'std::tr1::unordered_map' declared here
  class unordered_map
        ^
  1 error generated.`
  </pre>

**Comment by LeFroid** [comment]
What version of clang do you have?
Also, could you try reverting your changes in UnorderedMapSet.h and see if adding
"set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++")" to your CMakeLists.txt will fix any build errors you have?

I ask because I don't need these patches to build mangos two (essentially the same thing) and my machine is running FreeBSD 10.1 with clang/llvm 3.4

**Comment by Foereaper** [comment]
Zero, One and Two all use the exact same build system, thus if it works on two, it should also work on the other ones

**Comment by LeFroid** [comment]
It should, which is why I would like to know whether or not adding
set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++")
to your CMakeLists.txt file will fix your build errors without applying these patches.

As a side note, it would probably be easy to have a cmake macro that would set the CMAKE_CXX_FLAGS to the above line if it detects a freebsd system

**Comment by H0zen** [comment]
@LeFroid 
Adding `set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++")` to CMakeLists.txt gives the following:

<pre>Scanning dependencies of target genrev
[  0%] Building CXX object CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.o
src/tools/genrevision/genrevision.cpp:25:10: fatal error: 'fstream' file not found
#include &lt;fstream&gt;
         ^
1 error generated.
</pre>

As stated above, the clang version is 3.4.1, FreBSD 9.3-RELEASE

**Comment by H0zen** [comment]
Update: Following the directions in http://lists.freebsd.org/pipermail/freebsd-stable/2012-May/067645.html the error regarding inclusion dissapeared. Waiting for compilation result

**Comment by LeFroid** [comment]
Sorry H0zen, I missed that part of your second comment.
Let us know how it goes because I'll write a macro to include that definition by default on FreeBSD if it works for you.

**Comment by Foereaper** [comment]
How did the compile end up?

**Comment by LeFroid** [comment]
I'm assuming everything went well.
I added a cmake macro for freebsd on two, if anyone with access to the realmd repo and the other mangos branches would like to merge my last commit to the rest of the project that would be great.

**Comment by billy1arm** [comment]
I have applied all the relevant changes so i'm closing it. If i've missed anything, please let me know

**Pull request closed without merging**
