### PR TITLE
Updating the player saving SQL code

### PR DESCRIPTION
**Pull request by The-Great-Sephiroth**
I updated the SQL code used to save players to the database from two separate statements to a single one. This also eliminates deleting a character just to save it. This will allow for database normalization and optimization. This compiles and installs fine on my Linux server.

### CODE REVIEW

**Comment by Salja** [comment]
thanks for you work i check this on weekend and give you here reply

**Comment by The-Great-Sephiroth** [comment]
If this is to your satisfaction I will go through and update all of the sections of code like this. If the original author had wanted to delete and re-add stuff then he or she should have used "REPLACE INTO", which deletes and re-inserts with a single statement. This method will allow me to optimize the database though.

**Comment by The-Great-Sephiroth** [comment]
I see that you closed this pull request but what were your findings? Did it work in a fashion that is acceptable to you? If it did I will be very anxious to update more of the code and then optimize the database.

**Comment by Salja** [comment]
ups sorry ^^ my fail the code looks good atm i make some tests with this i give you feedback this week

**Comment by The-Great-Sephiroth** [comment]
Any word on this yet?

**Comment by The-Great-Sephiroth** [comment]
Did you test this? I have it running on my server this way with no issues that I have noticed. If this is going into the main code I can write some SQL that will optimize the databases.

**Pull request closed without merging**
