### PR TITLE
fix new mineral spawn system

### PR DESCRIPTION
**Pull request by Evildead666**

### CODE REVIEW

**Comment by The-Great-Sephiroth** [comment]
I just pulled this into my repo, which is a fresh clone of R20. I will build this now and test all weekend.

**Comment by billy1arm** [comment]
@The-Great-Sephiroth @Evildead666 - Any news ?

**Comment by The-Great-Sephiroth** [comment]
Crap! Forgot to reply. It is golden on my end. No issues whatsoever.

**Comment by Evildead666** [comment]
Thank you for testing.

**Pull request merged**
