### PR TITLE
[build] Add Docker files & launch script

### PR DESCRIPTION
**Pull request by tazjin**
(see comment below for more info)

---

This adds a Dockerfile for automated builds of MangosZero on Docker Hub.

A launch script is included that will fork a realmd into the background
and run mangosd as the foreground process.

Mangos is compiled and installed into `/opt/mangos`. The source is still
present in the `/opt/mangos/src` folder, all binaries are installed in
`/opt/mangos/bin`.

The image expects three possible volumes:

/opt/mangos/etc - Required. Configuration is mounted here

/opt/mangos/data - Required. Maps, DBCs etc. go here (can be mounted
as an empty host folder / data container)

/opt/mangos/wow - Optional, mount a World of Warcraft installation into
this folder and the launch script will extract and assemble necessary
maps, DBCs etc from it.

Using the image is relatively simple. The same container runs realmd and
mangosd, so the most important thing is to forward the container ports
properly.

If you set Mangos to connect to MariaDB / MySQL on `localhost` you also
need to forward the SQL socket into the container.

An example:

```
docker run --restart="always"
-v /var/lib/mysql/mysql.sock:/var/run/mysqld/mysqld.sock
-v ~/mangosdata:/opt/mangos/data
-v ~/mangosconf:/opt/mangos/etc
--name mangos-server
-p 3724:3724 -p 8085:8085
tazjin/mangoszero
```

### CODE REVIEW

**Comment by tazjin** [comment]
I decided to get this to run in a [Docker](https://www.docker.com/) container because it makes the setup so much easier once you've got MaNGOS to build correctly. This adds the files required for building Docker images off releases, but I've only tested it with the `Rel20Warden` -branch (shouldn't that be a tag? Is there some info about the release structure anywhere?).

An example of an automated build on Docker Hub can be [found here](https://registry.hub.docker.com/u/tazjin/mangoszero/build_id/23361/code/bwgr78y6nuy3m9wrgepflv/)

Most likely this Dockerfile would also work on `master`, unless some of the `cmake`-flags have changed.

**Comment by The-Great-Sephiroth** [comment]
I personally have never even heard of Docker or seen it used in all my years in the Unix/Linux industry, and to me it seems kind of like what systemd is trying to do: Unify packages across distros. Well, one of the many things it is trying to do, anyway.

I would not install to /opt. Most systems I work with have smaller partitions with /opt in them and MaNGOS could fill those partitions. I would install (as I do) to the proper binary location. This would normally be /usr or /usr/local. This would place everything into the correct locations. It is rare to see a large /opt partition in my experience.

You could also place the configuration files in /etc using the CONF_DIR directive in CMake so it is integrated more tightly. You could also use /var/log for the logs, or create something like /var/log/mangos for the multiple logs it produces. I do.

_UPDATE_

After looking over your script, I see some other issues. For one, it is Debian-only and does not appear to be POSIX-compliant. It also attempts to do things automatically, without asking the user, which may cause issues. For example, I use backports on my Debian systems and your script would give me grief when trying to install the regular LUA/build tools/etc packages. On top of that, it assumes that when the server is started, you want to extract all of the client data. This could bog down a server for some time. I would not do this personally.

Finally, we have a Linux script that does this and much more that has been developed for a while now. The PR is awaiting approval and you can check it out if you want. Integrating that script into Docker may be the ideal thing to do. This other script can be run without even cloning the repo, or after cloning. It handles everything including database install and/or updates. The only thing it does not do at this time, is map/vmap/mmap extraction, which is being integrated now.

**Comment by tazjin** [comment]
@The-Great-Sephiroth Hej! I assumed some familiarity with Docker, sorry - let me explain.

The point of Docker is to package entire applications in images, meaning you have a bunch of filesystem layers with the whole distribution + your application + the dependencies you need as an atomic unit (an _image_). These can be run on any machine running the Docker daemon (as a _container_) without actually adding any of the files in the container filesystem to the host filesystem.

This is not related to any init-system or package manager, as those things happen at a higher level than containers. (e.g. `systemd` could be running _in_ a container)

Basically on a machine running Docker (or on cloud-hosting services supporting Docker) this would simplify the MaNGOS-setup to something close to `docker run mysql && docker run mangoszero`, minus the effort required for setting up the actual database.

Might sound a bit strange if you haven't worked with containers before, but I recommend [you give it a try](https://www.docker.com/tryit/).

---

To address some specific points you mentioned:
1. The filesystem layout used in the `Dockerfile` affects the inside of the container only, not the host. Thus, keeping everything in `/opt` gives an easier overview and is unrelated to the partitions of the host. Extracted maps and such are not actually kept in `/opt` on the container, rather they are mounted into it from either the host or another container. (See [Docker Volumes](https://docs.docker.com/userguide/dockervolumes/))
2. The base image chosen for this is Debian and does not affect the host. Same goes for packages installed in the container, using backports on your host doesn't break the image (or vice-versa).
3. Docker launch scripts are supposed to do things automatically, as the intention is for them to be able to restart automatically and / or launch in the background without user interaction. The script will only attempt to extract data if it doesn't find the minimum data required (DBCs and maps).
4. The Linux script in the other PR is handling the usecase of running MaNGOS directly on the host. That's not the case with Docker, and Docker images should be kept as simple as possible.

**Comment by The-Great-Sephiroth** [comment]
Sounds like virtualization to me then. My servers both at home and at my client locations are virtualized and have been for ages. If it is cloud-based, not many users do that to my knowledge. I personally cannot find anybody else using Docker, but I did ask about it with the other developers. I would still maintain that it needs to be POSIX-compliant and it should ask the user before doing anything. Init-scripts keep the server going on my end, another project I am going to be pushing soon. Oh, and I stand by the usage of correct locations for the paths and files. This is so any user may access the binaries and not need to change to a special directory.

**Comment by tazjin** [comment]
Containerization is not virtualization, because nothing is being simulated. It's the actual kernel running in a different namespace. As I said, I'd recommend you to check out Docker even if your current company does not work with it.

Either way I'll keep a working Dockerfile in my fork and you guys can decide what to do with the PR.

**Comment by The-Great-Sephiroth** [comment]
I actually played with it and it seems like something I did in DOS with a coax network years ago. Back then I would have a system with a large capacity (250MB) disk or two in it, and I would put CD images or entire games on them. I could then map and use those games and images on any of the DOS systems in my lab, which was great!

I do see some potential for this and am discussing it with the head guys. I am low on the totem pole and do NOT make pull decisions. The rest of the team was out and about this week and I was simply voicing my thoughts on it. I do see this as being VERY useful in a distributed environment, but I personally don't know of any home users who would toy with it much.

**Pull request closed without merging**
