### PR TITLE
support 1.12.3.6141

### PR DESCRIPTION
**Pull request by ghost**
at 2006/11/14 , blizzard and the9 released 1.12.3.6141 client in china

### CODE REVIEW

**Comment by Salja** [comment]
you have a link for the patch .exe ?

**Comment by ghost** [comment]
I uploaded the patch "wow-1.12.3.6141-zhcn-patch.exe" to microsoft skydrive: 

http://sdrv.ms/WB8Joy

But you may need the whole client to run, because it's a chinese localized version, if you need the whole client, I'll upload it for you

**Comment by Salja** [comment]
thanks is ok i will test it today wehn works i push to master thanks =)

**Comment by ghost** [comment]
:  )

**Comment by ghost** [comment]
I also uploaded the wow.exe(1.12.3.6141) to http://sdrv.ms/Wp9IgF
I renamed the wow.exe(1.12.3.6141) to wow_1.12.3.6141.exe, then copied it to 1.12.1.5875's directory, and run it, it started successfully, hope it useful, thank you :  )

**Comment by Salja** [comment]
Thank you added in [z2291]

**Comment by ghost** [comment]
My pleasure! and thank you for the comment!

**Pull request closed without merging**
