### PR TITLE
[CMake/Eluna] Make Eluna optional when compiling

### PR DESCRIPTION
**Pull request by lfxgroove**
Would be super if @Rochet2 and @Foereaper could test these on their machines as well. Thanks!

### CODE REVIEW

**Comment by Foereaper** [comment]
As discussed earlier, the options should be opt out, not opt in :)

**Comment by lfxgroove** [comment]
@Foereaper that should fix it, anything else?

**Comment by Foereaper** [comment]
Looks good, great job! Has it been tested just to make sure it all works?

**Comment by lfxgroove** [comment]
Was hoping you could have a go at it pretty please? As i don't have a database i can run against atm, trying to get it up currently.

**Comment by Foereaper** [comment]
I only have a windows setup right now, cmake still doesn't work for win builds does it?

**Comment by lfxgroove** [comment]
Awh darn, don't think it does :( I've tried the compilation part at least and it seems to be compiling the right stuff. Perhaps @billy1arm can give it a go until i get a environment set up?

**Comment by Foereaper** [comment]
I will set up a test environment for Linux soon-ish.. Need to get a KVM switch first though.

**Comment by Foereaper** [comment]
Tested and verified working

**Comment by billy1arm** [comment]
manually merged

**Pull request closed without merging**
