### PR TITLE
Add Instant Flight Paths

### PR DESCRIPTION
**Pull request by ghost**
Your bird can reach their destinations at once

### CODE REVIEW

**Comment by The-Great-Sephiroth** [comment]
Are you saying that flights instantly arrive at their destination? That is not how the original release of WoW worked. There was a bug that allowed you to logout in flight and then log back in and be at your destination, but that was patched ages ago.

**Comment by ghost** [comment]
this looks more like a custom feature and should be set to 0 by default not 1

**Comment by The-Great-Sephiroth** [comment]
I see. I also see "BOLL" in the code. Is that supposed to be "BOOL" as in boolean?

**Comment by ghost** [comment]
it's more of a codestyle, you can see the enum is enum eConfigBoolValues there is also float etc

**Comment by ghost** [comment]
Yes, it's very interesting, isn't it o(∩_∩)o

**Pull request closed without merging**
