### PR TITLE
Greylevel fix

### PR DESCRIPTION
**Pull request by Evildead666**
Fixing greylevel formula to pre TBC version. Solving the problem with not getting soulshards from green mobs, probably fixing the problem with spirit tap aswell.

### CODE REVIEW

**Comment by Salja** [comment]
looks good you have a source what you use for the formula ?

**Comment by Evildead666** [comment]
Main source is Mangos itself the visual greylevel is indeed correct, also calculated xp.
Simply try getting a shard with a level 60 from a green level 48 mob.
Incendosaurs are good for testing.
http://www.wowwiki.com/Formulas:Mob_XP under Look under Level 60 and up characters it confirms the greylevel change from TBC.
I also had an old table from pre TBC with lowest green levels for each playerlevel which i used fro recalculating the formula myself.
Try to find the table at the moment.

**Comment by Evildead666** [comment]
http://www.wowpedia.org/index.php?title=Experience_point&oldid=211005
Found it, but note the table shows the lowest greenlevels not the highest greylevel

**Comment by Salja** [comment]
We discuss in skype atm over this i give them modest later thanks for this sources

**Comment by Salja** [comment]
news here some more sources ?

**Pull request closed without merging**
