### PR TITLE
Build warning eliminated (storing int in bool)

### PR DESCRIPTION
**Pull request by Chuck5ta**
Original code attempted to copy the contents of an integer variable into
a boolean variable.

Seeing as the check is for NOT equal to 0 (FALSE), the contents of the
boolean (CONF_allow_float_to_int) will be TRUE, therefore you might as
well explicitly state the this instead of attempting to force it.

### CODE REVIEW

**Comment by Rochet2** [comment]
In the whole file its originally true, and can be only set to true by a param.
So its never false?..

Not saying your logic is wrong, but that I dont see the use of the variable if it cant be affected and will be true always..
Did not check other files than the one at hand.

**Comment by The-Great-Sephiroth** [comment]
If it is always true, why is it there? Seems odd. Maybe Luda or Salja originally had other plans for it.

**Comment by Salja** [comment]
Not my work xD :-) but check out its antz work https://github.com/Chuck5ta/server/commit/f2115da24b59ede9180e7e4f21f80642fd798487 Hihi

**Comment by billy1arm** [comment]
Which was pulled from the Original Rel18 by theLuda when he attempted to rewrite the parameter passing for the util. 

But the code remains fairly similar to the original code still used by other projects.

So no idea !!

We can revisit this when we start the tool cleanup cycle, currently scheduled for Rel21

**Pull request closed without merging**
