### PR TITLE
[PATCH] Add the ability to specify in the configuration file the cost and the required level for training and acquiring both normal and epic mounts.

### PR DESCRIPTION
**Pull request by cxtal**
Add the ability to specify in the configuration file the cost and the required level for training and acquiring both normal and epic mounts.

For more information, please see the open issue at: https://github.com/mangoszero/server/issues/164

### CODE REVIEW

**Comment by lfxgroove** [comment]
Looks good to me :)

**Comment by billy1arm** [comment]
hi @evacomaroski , after reviewing this, why can't you just update the database...

Take item 8628 reins of frostsabres.
UPDATE `item_template` SET `BuyPrice` = 1000 AND `RequiredLevel`=20 WHERE `entry`=8628;

Please realise if you begin to modify wow you will have to delete your wtf (cache) because it precaches values, and will display these ingame even after changes.

**Comment by GableTheSnail** [comment]
@billy1arm Even if you set the buy-price in the database, for both the items and the training price, the trainer will not allow you to train the riding skill (even if you delete your cache). The item will appear as available but you will not be able to train it. It seems to be tied-in to the DBC.

**Comment by GableTheSnail** [comment]
@billy1arm One thing that I remember from two years ago (?), was that 2.4.3 (the equivalent of mangosone) did not require a code-level patch. Instead you could just edit the database like you said. I cannot confirm that though because back at that time we were running TrinityCore so there may be some differences.

On mangozero, I first changed the database, then the "Train" button did not activate (requirements were updated though), so I created the patch instead. I did see some references to Spell.dbc when reading through the code, so it might be tied to the DBC.

It may be that mangosone would settle for just a database change, however mangoszero definitely needs the patch. I have no clue whatsoever about WoTLK and up...

All cases considered, given that mangoszero does not accept just a database alteration, I find it more elegant to have a toggle for it in the configuration file.

**Comment by billy1arm** [comment]
@evacomaroski thank you for your continued work. I am hoping to incorporate this into the Rel19 branch today, failing that - it will be an update for Rel19

**Comment by GableTheSnail** [comment]
@billy1arm Thanks. I hope it helps someone out there. :-)

**Comment by billy1arm** [comment]
@evacomaroski - Added this manually to Rel20 - many thanks

**Pull request closed without merging**
