### PR TITLE
Add Linux build script and directory

### PR DESCRIPTION
**Pull request by The-Great-Sephiroth**
Created a build directory for Linux users and added the new Linux automation script to it.

### CODE REVIEW

**Comment by billy1arm** [comment]
@The-Great-Sephiroth - Has this been updated to support the New db file layout for Rel20 ?

**Comment by The-Great-Sephiroth** [comment]
I had not realized that everything was moved to the DB. I will update and do a fresh PR tomorrow.

**Comment by The-Great-Sephiroth** [comment]
Alright, I updated the Linux script to work with the new DB file layout and I also fixed the existing Linux shell scripts for the tools. This works on my end in Debian Wheezy 64bit and Gentoo 64bit.

**Comment by The-Great-Sephiroth** [comment]
Is there a problem with this PR? I have verified that it works on R20 correctly. If something is wrong, let me know and I will fix it.

**Comment by billy1arm** [comment]
I have merged for now, but hoping the changes made in the .sh files will not break on windows.

Something that needs testing

**Comment by The-Great-Sephiroth** [comment]
This will not affect Windows at all. The only file I added was the one I wrote, and the corrections in the existing shell scripts are actual shell scripts. I do not believe they're used in Windows. If they are it should work fine though.

**Comment by billy1arm** [comment]
I use the shell scripts on windows :)

I have confirmed that they still work as expected

**Comment by The-Great-Sephiroth** [comment]
Great! I have not had much time lately. The issue is that Windows looks for commands in the current directory and Linux does not. If you just type a binary name in a script without prefixing it with "./", t looks in places like /bin, /usr/bin, etc and fails to run the program. That prefix tells it to look in the script directory. Glad we're good!

**Pull request merged**
