### PR TITLE
Patch to fix auras killing pets from causing a core dump

### PR DESCRIPTION
**Pull request by The-Great-Sephiroth**
This is a patch that was suggested by Rochet2 but never tested or worked. I changed it a bit so it would work correctly and it has solved auras killing pets causing core dumps on my end in Debian GNU/Linux. If you have questions, ask.

### CODE REVIEW

**Comment by Rochet2** [comment]
Have you tested killing player pets as well?
A problem with my original solution (which was just to fix  the crash at all) was that killed pets also disappeared instantly then (player pets), even though they should stay to be rezzed by player.

**Comment by The-Great-Sephiroth** [comment]
Sorry, I did not get an email about your question. My pet appeared to stay. Let me test a few times and I will let you know. I am going to test with ".die" since it is just me anyway.

**Comment by The-Great-Sephiroth** [comment]
Alright, here are the results, one of which is a bug-fix! Prior to this patch if I modified my speed and outran my pet, it would not despawn, I could not summon it, and I was hosed as a hunter or warlock. The fix was to logout and back in. This no longer happens. Now when you outrun the pet it despawns and you can summon it again.

However, if you KILL the pet, it does fade away. This is only half of a bug. You see, I have been playing prior to this patch and noted that if my pet fell in combat and my battle took a bit longer, the pet was gone anyway, so I would whistle to call him back with 1hp. This happens every time now.

Now, the second issue will take a bit of code to correct. First, the pet would have to be a HUNTER pet to not fade away. Second, how long should the pet corpse lay around? I admit that I do not remember how long the corpses lasted in official. I do seem to remember that if you waited to long the corpse would go away and you couldn't whistle it back. You had to go to a trainer or somebody and use a dialog option to recover it. My memory is hazy however. I do note that certain NPCs in game offer to recover lost pets for you already, but there is no dialog option to do this.

Now, this patch DOES correct the core crash. That is the big thing. It also inadvertently fixes the "outrun your pet" bug. I'd say it gives us a base to build on while fixing two bugs, but it is your call. I will look into handling hunter pets dying after I finish the MySQL update.

**Comment by Rochet2** [comment]
Yes, I also believe fixing the crash is essential, but was just wondering, especially if you had some insight : )

**Comment by The-Great-Sephiroth** [comment]
I will work on this if nobody beats me to it once the database and spell system are good.

**Comment by The-Great-Sephiroth** [comment]
Also, I have tested this under Windows as well, and it has not caused any issues. This was in an XP virtual machine, not on bare metal. My work systems run Linux and my only Windows systems are either virtual, or my gaming rigs.

**Comment by The-Great-Sephiroth** [comment]
Is there a problem with this PR? I have been running it for two weeks without any negative effects and the crashes are gone.

**Comment by Rochet2** [comment]
The pet disappearing.

**Comment by The-Great-Sephiroth** [comment]
You just whistle for it and it returns. It doesn't go away permanently. This is a crash fix. This is not a three-week project with 100% fixes for all pet issues. The goal was to stop the constant crashing almost every time a pet was killed by a DoT. That goal was accomplished. It is a LOT easier to whistle your pet back then to restart your server and lose ten minutes or so of play.

With that said, should core crash fixes now contain 100% Blizz-like functionality? This has not caused issues. It is a core crash fix. I am currently working on the rest. So do we want the crash-fix or are we waiting for a drop-in solution to all pet problems? I am offering a small piece of the puzzle here.

**Comment by Foereaper** [comment]
According to a chat had the other day in the development chat, it was pointed out that this causes a memory leak.

"from runtime, this is where its pointing to. https://github.com/The-Great-Sephiroth/server/commit/68f55260252de203387c13a9ba8ab1bf0d3765a2#diff-2c87205b23d16e38747296126b3d005bR552

i think there should be a break on the case in that function."

**Comment by The-Great-Sephiroth** [comment]
Now THAT is a different story. I have not noticed a leak. I will jump on this immediately. Shouldn't these kinds of things be noted on the forum or in the PR thread here?

How do I trigger the leak? I want to test this in GDB. The server has been running, non-stop, on my hardware for two weeks without issue but I have not checked memory. I will check when I get home. Thanks for clearing up the issue. it WILL be fixed today.

**Comment by Foereaper** [comment]
I am not sure, I just noticed when the discussion was done, at the same time Nymph2013 commented on your PR. Not sure why he did not mention the leak here as well.

"[19.12.2014 19:49:50] Matt: was testing Sephiroth pet crash temp fix and found a memory leak within it. once the pet despawns, the memory of the server goes crazy."

**Comment by The-Great-Sephiroth** [comment]
I do not have this issue on GNU/Linux. Are you saying I simply have to let the pet die and the memory usage should go up or something? I am using around 800MiB on the server, where it normally sits. Can we peg the leak down to this patch positively?

**Comment by billy1arm** [comment]
@Nymph2013 - Can you explain what you did to cause this ?

**Comment by The-Great-Sephiroth** [comment]
Guys, I am not seeing abnormal memory issues using my repo. My repo is currently a clone of official plus this patch. Can somebody else clone my repo and attempt to create this memory issue? In Linux it appears to be fine, which may indicate it is a Windows library with an issue or it could have been a fluke and this patch does work.

_EDIT_

Here is some output. The mangosd process has been up for about two weeks, the server for almost a month. Note that mangosd is only using about one-fifth of the RAM allocated to the VM, which is 1.25GiB. That means it is using around 256MB. This is with several players on, hence the CPU usage being a tad higher than normal.

``` C
top - 18:38:09 up 24 days, 22:50,  1 user,  load average: 0.30, 0.29, 0.30
Tasks:  78 total,   1 running,  77 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.4 us, 12.8 sy,  0.0 ni, 76.1 id,  1.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   1229244 total,  1141632 used,    87612 free,   130256 buffers
KiB Swap:  1978364 total,    28196 used,  1950168 free,   612412 cached

  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND
31186 -----     20   0  356m 251m 6344 S  20.9 20.9   21211:05 mangosd
31179 -----     20   0 18984 2836 2112 S   1.3  0.2 201:57.71 realmd
22583 -----     20   0  9264 1476  892 S   0.3  0.1   0:00.01 sshd
```

**Comment by Meltie2013** [comment]
@billy1arm The memory leak only happens right after the pet dies/despawns. Its only there for a few seconds and goes away. Its not a perm leak. Its only "During the Death or Despawn" of the pet. Its a 150mb spike during that time.

Test System: Debian 7 (wheezy)

**Comment by The-Great-Sephiroth** [comment]
Ah so it isn't permanent. That may be why I am missing it. Let me do some testing and I'll fix that. I thought you guys were not happy because the pet corpse didn't lay around, I didn't realize we had an issue like this.

**Comment by The-Great-Sephiroth** [comment]
I am only seeing a few MB spike on my server. Granted, it could have been there beforehand and I would not have known, but if you say it is abnormal so be it. I am seeing a 16~20MB spike when a pet despawns. As such, my first check will be removing the return statement and replacing it with a break statement. I will then check again. If it continues, I will have to dig into the code and see what is causing us issues.

**Comment by The-Great-Sephiroth** [comment]
That seems to have fixed it. I tested by starting a duel, having my fiance simply shoot my pet (pet on passive) until it died, and watched the terminal resources. No spike at all. This leads me to believe that this was indeed an issue before. Why? Because in that original 'if' block, it would return after the unsummon command, which is why I left it that way. Perhaps returning every time was causing the issue though. I will test this tomorrow and if AI pets are good also, I'll update the PR. Thanks for the information!

**Comment by billy1arm** [comment]
@The-Great-Sephiroth great stuff, thanks guys - give me a nudge when it's done and i'll merge it in

**Comment by The-Great-Sephiroth** [comment]
Done, this has worked for several hours and not one spike. I just made the commit, so will you guys give it a shot and merge it or let me know if something else is wrong? It appears to be fine here, but I may not be looking for something you will spot.

_UPDATE_

My fiance and I have been on and playing our hunters, purposely allowing the pets to die. No spikes I can see. Has anybody else tried yet?

**Comment by billy1arm** [comment]
ToDo: Pets despawn immediately

**Pull request merged**
